In [152]:
# Logistic Regression:
# Apply logistic regression on the Loan dataset with
# "Decision" as the dependent variable. Do the necessary
# one-hot encoding for the categorical variables and
# discard the irrelevant variables. Use whatever
# libraries are appropriate when coding in Python.

In [153]:
# all necessary imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [154]:
dataset = pd.read_excel('loan.xlsx')
new_dataset = dataset
dataset.head()

,Sex,Age,Time_at_address,Res_status,Telephone,Occupation,Job_status,Time_employed,Time_bank,Liab_ref,Acc_ref,Home_Expn,Balance,Decision
0,M,50.750000,0.585,owner,given,unemploye,unemploye,0,0,f,given,145,0,reject
1,M,19.670000,10.000,rent,not_given,labourer,governmen,0,0,t,given,140,0,reject
2,F,52.830002,15.000,owner,given,creative_,private_s,5,14,f,given,0,2200,accept
3,M,22.670000,2.540,rent,not_given,creative_,governmen,2,0,f,given,0,0,accept
4,M,29.250000,13.000,owner,given,driver,governmen,0,0,f,given,228,0,reject

In [155]:
# dataset summary
dataset.describe()

,Age,Time_at_address,Time_employed,Time_bank,Home_Expn,Balance
count,429.000000,429.000000,429.000000,429.000000,429.000000,429.000000
mean,31.510163,4.650758,1.871795,2.279720,176.727273,898.382284
std,11.843595,4.804037,3.254023,3.966105,142.590659,3814.565340
min,15.170000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,22.670000,1.000000,0.000000,0.000000,80.000000,0.000000
50%,28.500000,2.750000,1.000000,0.000000,160.000000,10.000000
75%,38.250000,7.000000,2.000000,3.000000,272.000000,484.000000
max,76.750000,25.209999,20.000000,23.000000,760.000000,51100.000000

In [156]:
# finding out null data => missing data
dataset.isnull().sum()

# inference => no missing data

Sex                0
Age                0
Time_at_address    0
Res_status         0
Telephone          0
Occupation         0
Job_status         0
Time_employed      0
Time_bank          0
Liab_ref           0
Acc_ref            0
Home_Expn          0
Balance            0
Decision           0
dtype: int64

In [157]:
dataset.shape

# before calculating correlation, we shall one hot encode Sex, Res_Status, Telephone, Occupation, Job Status, Acc_ref, Decision

(429, 14)

In [158]:
# one hot encoding
onehot_encoder = OneHotEncoder(handle_unknown='ignore')

# label encoder
label_encoder = LabelEncoder()

In [159]:
# sex
print('Sex: ', dataset['Sex'].nunique())

new_dataset['Sex'] = label_encoder.fit_transform(dataset['Sex'])

Sex:  2

In [160]:
# Res_Status
print('Res_status: ', dataset['Res_status'].nunique())

dataset['Res_status'] = label_encoder.fit_transform(dataset['Res_status'])

Res_status:  2

In [161]:
# Telephone
print('Telephone: ', dataset['Telephone'].nunique())

dataset['Telephone'] = label_encoder.fit_transform(dataset['Telephone'])

Telephone:  2

In [162]:
# Acc_ref
print('Acc_ref: ', dataset['Acc_ref'].nunique())

dataset['Acc_ref'] = label_encoder.fit_transform(dataset['Acc_ref'])

Acc_ref:  2

In [195]:
# Liab_ref
print('Liab_ref: ', dataset['Liab_ref'].nunique())

dataset['Liab_ref'] = label_encoder.fit_transform(dataset['Liab_ref'])

Liab_ref:  2

In [196]:
# Decision
print(dataset['Decision'].dtype)
print('Decision: ', dataset['Decision'].nunique())

dataset['Decision'] = label_encoder.fit_transform(dataset['Decision'])

int32
Decision:  2

In [197]:
# Job_status

print('Job_status: ', dataset['Job_status'].unique())

KeyError: 'Job_status'

In [198]:
# Occupation
print('Occupation: ', dataset['Occupation'].unique())

# dataset['Occupation'] = label_encoder.fit_transform(dataset['Res_Status'])

KeyError: 'Occupation'

In [199]:
features_array = onehot_encoder.fit_transform(dataset[['Job_status', 'Occupation']]).toarray()

KeyError: "None of [Index(['Job_status', 'Occupation'], dtype='object')] are in the [columns]"

In [200]:
feature_labels = ['governmen', 'military', 'private_s', 'retired', 'self_empl',
        'student', 'unemploye', 'creative_', 'driver', 'executive', 'guard_etc', 'labourer',
        'manager', 'office_st', 'productio', 'professio', 'sales',
        'semi_pro', 'unemploye']
feature_labels

['governmen',
 'military',
 'private_s',
 'retired',
 'self_empl',
 'student',
 'unemploye',
 'creative_',
 'driver',
 'executive',
 'guard_etc',
 'labourer',
 'manager',
 'office_st',
 'productio',
 'professio',
 'sales',
 'semi_pro',
 'unemploye']

In [201]:
features = pd.DataFrame(features_array, columns = feature_labels)

In [202]:
dataset = pd.concat([dataset, features], axis=1)

In [203]:
dataset.drop(['Occupation','Job_status'], axis=1, inplace=True)

KeyError: "['Occupation' 'Job_status'] not found in axis"

In [204]:
dataset.columns

Index(['Sex', 'Age', 'Res_status', 'Time_employed', 'Time_bank', 'Liab_ref',
       'Acc_ref', 'Home_Expn', 'Balance', 'Decision', 'governmen', 'military',
       'private_s', 'retired', 'self_empl', 'student', 'unemploye',
       'creative_', 'driver', 'executive', 'guard_etc', 'labourer', 'manager',
       'office_st', 'productio', 'professio', 'sales', 'semi_pro', 'unemploye',
       'governmen', 'military', 'private_s', 'retired', 'self_empl', 'student',
       'unemploye', 'creative_', 'driver', 'executive', 'guard_etc',
       'labourer', 'manager', 'office_st', 'productio', 'professio', 'sales',
       'semi_pro', 'unemploye'],
      dtype='object')

In [205]:
# data prepared for correlation

corr = dataset.corr()
corr

,Sex,Age,Res_status,Time_employed,Time_bank,Liab_ref,Acc_ref,Home_Expn,Balance,Decision,...,executive,guard_etc,labourer,manager,office_st,productio,professio,sales,semi_pro,unemploye
Sex,1.000000,0.025167,0.121713,0.077239,-0.072303,0.010508,0.095826,0.115355,-0.045248,0.052564,...,0.033932,0.022947,-0.008220,0.141564,-0.239058,0.089171,-0.028788,-0.116177,0.057602,-0.085110
Age,0.025167,1.000000,-0.080265,0.426890,0.208736,0.049109,-0.040445,-0.072254,0.101819,-0.181241,...,0.195693,0.028675,-0.035318,0.056127,-0.085265,-0.025142,-0.008012,-0.061906,-0.002900,0.210038
Res_status,0.121713,-0.080265,1.000000,-0.074690,-0.132413,0.018827,-0.000201,-0.006477,-0.068829,0.139104,...,-0.013801,-0.059316,0.103196,-0.007468,-0.141542,0.015006,0.058154,-0.043244,0.012631,0.048437
Time_employed,0.077239,0.426890,-0.074690,1.000000,0.291542,0.122561,-0.025000,-0.110933,0.112719,-0.339833,...,0.158402,-0.048504,-0.076296,0.085916,0.045731,-0.005221,0.065455,-0.080398,0.001919,-0.042615
Time_bank,-0.072303,0.208736,-0.132413,0.291542,1.000000,0.051000,-0.158334,-0.111761,0.153435,-0.455942,...,0.070908,-0.079085,-0.102461,-0.004365,0.115238,-0.035694,0.030341,-0.087884,0.042998,-0.026283
Liab_ref,0.010508,0.049109,0.018827,0.122561,0.051000,1.000000,0.033197,0.127133,-0.013128,-0.068508,...,-0.047445,0.051444,0.044265,0.041821,-0.005693,0.037271,0.030484,-0.057168,-0.003053,-0.086354
Acc_ref,0.095826,-0.040445,-0.000201,-0.025000,-0.158334,0.033197,1.000000,0.096426,-0.065739,0.106354,...,0.023691,-0.017403,0.029235,0.254292,-0.071914,-0.036777,-0.063317,-0.077889,-0.019012,-0.041226
Home_Expn,0.115355,-0.072254,-0.006477,-0.110933,-0.111761,0.127133,0.096426,1.000000,0.080366,0.087311,...,-0.022788,0.070586,-0.024372,0.121765,-0.017424,0.048673,0.112318,-0.049655,0.094591,-0.139506
Balance,-0.045248,0.101819,-0.068829,0.112719,0.153435,-0.013128,-0.065739,0.080366,1.000000,-0.191858,...,0.153182,-0.025923,-0.053978,-0.023879,-0.008416,-0.028536,0.004505,-0.028959,0.138420,-0.020692
Decision,0.052564,-0.181241,0.139104,-0.339833,-0.455942,-0.068508,0.106354,0.087311,-0.191858,1.000000,...,-0.067796,0.131258,0.107222,0.029066,-0.133674,-0.028458,-0.165153,0.033932,-0.134504,0.173276
governmen,-0.071354,0.011700,0.006508,0.135908,0.097365,-0.041223,-0.066981,0.059496,-0.042154,-0.158575,...,-0.079377,-0.036600,0.019390,-0.080452,0.179558,-0.050329,0.191944,-0.089877,0.117460,-0.133296
military,0.033287,-0.054508,-0.026127,-0.027837,-0.003413,0.052702,-0.013490,-0.005677,-0.003950,0.043507,...,-0.010689,-0.014407,-0.015924,-0.012773,-0.017357,-0.016547,-0.010966,-0.013490,-0.010689,-0.013254
private_s,0.043589,-0.247584,-0.021999,-0.172712,-0.115185,0.037822,0.089868,0.035104,-0.037121,0.044389,...,-0.190084,-0.203628,0.081608,0.130195,-0.004043,0.175375,-0.066073,0.163973,-0.030814,-0.348558
retired,0.021153,0.309407,-0.033319,0.265212,0.155554,-0.022658,-0.038472,-0.149999,0.049078,-0.083847,...,0.623377,-0.041086,-0.045412,-0.036426,-0.049501,-0.047189,-0.031274,-0.038472,-0.030483,-0.037799
self_empl,0.087138,0.114273,-0.007264,0.045330,0.030708,0.084938,0.010466,0.076962,0.127365,0.009342,...,0.010833,0.515114,-0.073270,-0.013948,-0.110322,-0.105172,-0.069701,-0.053673,-0.028552,-0.084243
student,-0.018208,-0.076762,0.045143,-0.042492,-0.035080,-0.012399,-0.030307,-0.043405,-0.016428,0.010385,...,0.491076,-0.032366,-0.035774,-0.028695,-0.038995,-0.037174,-0.024637,-0.030307,-0.024013,-0.029777
unemploye,-0.077631,0.203320,0.042843,-0.047159,-0.031069,-0.093314,-0.043119,-0.142259,-0.022504,0.178776,...,-0.061715,-0.083181,-0.061647,-0.073747,-0.100218,-0.095539,-0.063317,-0.077889,-0.061715,0.982505
creative_,0.092333,-0.100224,0.029843,-0.005600,0.103602,-0.034575,-0.036148,-0.088680,-0.004997,-0.032268,...,-0.115540,-0.155727,-0.172127,-0.138066,-0.187623,-0.178863,-0.118538,-0.145820,-0.115540,-0.143269
driver,0.056538,-0.061793,0.011242,-0.064149,-0.085321,0.041735,0.135115,-0.032013,-0.037821,0.078199,...,-0.043525,-0.058664,-0.064842,-0.052011,-0.070679,-0.067379,-0.044654,-0.054932,-0.043525,-0.053971
executive,0.033932,0.195693,-0.013801,0.158402,0.070908,-0.047445,0.023691,-0.022788,0.153182,-0.067796,...,1.000000,-0.065908,-0.072849,-0.058433,-0.079407,-0.075700,-0.050169,-0.061715,-0.048900,-0.060636
guard_etc,0.022947,0.028675,-0.059316,-0.048504,-0.079085,0.051444,-0.017403,0.070586,-0.025923,0.131258,...,-0.065908,1.000000,-0.098187,-0.078758,-0.107027,-0.102030,-0.067618,-0.083181,-0.065908,-0.081726
labourer,-0.008220,-0.035318,0.103196,-0.076296,-0.102461,0.044265,0.029235,-0.024372,-0.053978,0.107222,...,-0.072849,-0.098187,1.000000,-0.087051,-0.118297,-0.112774,-0.074739,-0.091941,-0.072849,-0.090332
manager,0.141564,0.056127,-0.007468,0.085916,-0.004365,0.041821,0.254292,0.121765,-0.023879,0.029066,...,-0.058433,-0.078758,-0.087051,1.000000,-0.094888,-0.090458,-0.059950,-0.073747,-0.058433,-0.072457
office_st,-0.239058,-0.085265,-0.141542,0.045731,0.115238,-0.005693,-0.071914,-0.017424,-0.008416,-0.133674,...,-0.079407,-0.107027,-0.118297,-0.094888,1.000000,-0.122927,-0.081468,-0.100218,-0.079407,-0.098465
productio,0.089171,-0.025142,0.015006,-0.005221,-0.035694,0.037271,-0.036777,0.048673,-0.028536,-0.028458,...,-0.075700,-0.102030,-0.112774,-0.090458,-0.122927,1.000000,-0.077664,-0.095539,-0.075700,-0.093867
professio,-0.028788,-0.008012,0.058154,0.065455,0.030341,0.030484,-0.063317,0.112318,0.004505,-0.165153,...,-0.050169,-0.067618,-0.074739,-0.059950,-0.081468,-0.077664,1.000000,-0.063317,-0.050169,-0.062209
sales,-0.116177,-0.061906,-0.043244,-0.080398,-0.087884,-0.057168,-0.077889,-0.049655,-0.028959,0.033932,...,-0.061715,-0.083181,-0.091941,-0.073747,-0.100218,-0.095539,-0.063317,1.000000,-0.061715,-0.076527
semi_pro,0.057602,-0.002900,0.012631,0.001919,0.042998,-0.003053,-0.019012,0.094591,0.138420,-0.134504,...,-0.048900,-0.065908,-0.072849,-0.058433,-0.079407,-0.075700,-0.050169,-0.061715,1.000000,-0.060636
unemploye,-0.085110,0.210038,0.048437,-0.042615,-0.026283,-0.086354,-0.041226,-0.139506,-0.020692,0.173276,...,-0.060636,-0.081726,-0.090332,-0.072457,-0.098465,-0.093867,-0.062209,-0.076527,-0.060636,1.000000
governmen,-0.071354,0.011700,0.006508,0.135908,0.097365,-0.041223,-0.066981,0.059496,-0.042154,-0.158575,...,-0.079377,-0.036600,0.019390,-0.080452,0.179558,-0.050329,0.191944,-0.089877,0.117460,-0.133296
military,0.033287,-0.054508,-0.026127,-0.027837,-0.003413,0.052702,-0.013490,-0.005677,-0.003950,0.043507,...,-0.010689,-0.014407,-0.015924,-0.012773,-0.017357,-0.016547,-0.010966,-0.013490,-0.010689,-0.013254
private_s,0.043589,-0.247584,-0.021999,-0.172712,-0.115185,0.037822,0.089868,0.035104,-0.037121,0.044389,...,-0.190084,-0.203628,0.081608,0.130195,-0.004043,0.175375,-0.066073,0.163973,-0.030814,-0.348558
retired,0.021153,0.309407,-0.033319,0.265212,0.155554,-0.022658,-0.038472,-0.149999,0.049078,-0.083847,...,0.623377,-0.041086,-0.045412,-0.036426,-0.049501,-0.047189,-0.031274,-0.038472,-0.030483,-0.037799
self_empl,0.087138,0.114273,-0.007264,0.045330,0.030708,0.084938,0.010466,0.076962,0.127365,0.009342,...,0.010833,0.515114,-0.073270,-0.013948,-0.110322,-0.105172,-0.069701,-0.053673,-0.028552,-0.084243
student,-0.018208,-0.076762,0.045143,-0.042492,-0.035080,-0.012399,-0.030307,-0.043405,-0.016428,0.010385,...,0.491076,-0.032366,-0.035774,-0.028695,-0.038995,-0.037174,-0.024637,-0.030307,-0.024013,-0.029777
unemploye,-0.077631,0.203320,0.042843,-0.047159,-0.031069,-0.093314,-0.043119,-0.142259,-0.022504,0.178776,...,-0.061715,-0.083181,-0.061647,-0.073747,-0.100218,-0.095539,-0.063317,-0.077889,-0.061715,0.982505
creative_,0.092333,-0.100224,0.029843,-0.005600,0.103602,-0.034575,-0.036148,-0.088680,-0.004997,-0.032268,...,-0.115540,-0.155727,-0.172127,-0.138066,-0.187623,-0.178863,-0.118538,-0.145820,-0.115540,-0.143269
driver,0.056538,-0.061793,0.011242,-0.064149,-0.085321,0.041735,0.135115,-0.032013,-0.037821,0.078199,...,-0.043525,-0.058664,-0.064842,-0.052011,-0.070679,-0.067379,-0.044654,-0.054932,-0.043525,-0.053971
executive,0.033932,0.195693,-0.013801,0.158402,0.070908,-0.047445,0.023691,-0.022788,0.153182,-0.067796,...,1.000000,-0.065908,-0.072849,-0.058433,-0.079407,-0.075700,-0.050169,-0.061715,-0.048900,-0.060636
guard_etc,0.022947,0.028675,-0.059316,-0.048504,-0.079085,0.051444,-0.017403,0.070586,-0.025923,0.131258,...,-0.065908,1.000000,-0.098187,-0.078758,-0.107027,-0.102030,-0.067618,-0.083181,-0.065908,-0.081726
labourer,-0.008220,-0.035318,0.103196,-0.076296,-0.102461,0.044265,0.029235,-0.024372,-0.053978,0.107222,...,-0.072849,-0.098187,1.000000,-0.087051,-0.118297,-0.112774,-0.074739,-0.091941,-0.072849,-0.090332
manager,0.141564,0.056127,-0.007468,0.085916,-0.004365,0.041821,0.254292,0.121765,-0.023879,0.029066,...,-0.058433,-0.078758,-0.087051,1.000000,-0.094888,-0.090458,-0.059950,-0.073747,-0.058433,-0.072457
office_st,-0.239058,-0.085265,-0.141542,0.045731,0.115238,-0.005693,-0.071914,-0.017424,-0.008416,-0.133674,...,-0.079407,-0.107027,-0.118297,-0.094888,1.000000,-0.122927,-0.081468,-0.100218,-0.079407,-0.098465
productio,0.089171,-0.025142,0.015006,-0.005221,-0.035694,0.037271,-0.036777,0.048673,-0.028536,-0.028458,...,-0.075700,-0.102030,-0.112774,-0.090458,-0.122927,1.000000,-0.077664,-0.095539,-0.075700,-0.093867
professio,-0.028788,-0.008012,0.058154,0.065455,0.030341,0.030484,-0.063317,0.112318,0.004505,-0.165153,...,-0.050169,-0.067618,-0.074739,-0.059950,-0.081468,-0.077664,1.000000,-0.063317,-0.050169,-0.062209
sales,-0.116177,-0.061906,-0.043244,-0.080398,-0.087884,-0.057168,-0.077889,-0.049655,-0.028959,0.033932,...,-0.061715,-0.083181,-0.091941,-0.073747,-0.100218,-0.095539,-0.063317,1.000000,-0.061715,-0.076527
semi_pro,0.057602,-0.002900,0.012631,0.001919,0.042998,-0.003053,-0.019012,0.094591,0.138420,-0.134504,...,-0.048900,-0.065908,-0.072849,-0.058433,-0.079407,-0.075700,-0.050169,-0.061715,1.000000,-0.060636
unemploye,-0.085110,0.210038,0.048437,-0.042615,-0.026283,-0.086354,-0.041226,-0.139506,-0.020692,0.173276,...,-0.060636,-0.081726,-0.090332,-0.072457,-0.098465,-0.093867,-0.062209,-0.076527,-0.060636,1.000000

In [206]:
# dropping columns based on correlations

# also dropping Time_at_address as it plays trivial role in decision making

dataset.drop(['Telephone', 'Time_at_address'], axis=1, inplace=True)

KeyError: "['Telephone' 'Time_at_address'] not found in axis"

In [207]:
dataset.columns

# inference => we have 33 variables

Index(['Sex', 'Age', 'Res_status', 'Time_employed', 'Time_bank', 'Liab_ref',
       'Acc_ref', 'Home_Expn', 'Balance', 'Decision', 'governmen', 'military',
       'private_s', 'retired', 'self_empl', 'student', 'unemploye',
       'creative_', 'driver', 'executive', 'guard_etc', 'labourer', 'manager',
       'office_st', 'productio', 'professio', 'sales', 'semi_pro', 'unemploye',
       'governmen', 'military', 'private_s', 'retired', 'self_empl', 'student',
       'unemploye', 'creative_', 'driver', 'executive', 'guard_etc',
       'labourer', 'manager', 'office_st', 'productio', 'professio', 'sales',
       'semi_pro', 'unemploye'],
      dtype='object')

In [208]:
dataset.head()

,Sex,Age,Res_status,Time_employed,Time_bank,Liab_ref,Acc_ref,Home_Expn,Balance,Decision,...,executive,guard_etc,labourer,manager,office_st,productio,professio,sales,semi_pro,unemploye
0,1,50.750000,0,0,0,0,0,145,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,19.670000,1,0,0,1,0,140,0,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,52.830002,0,5,14,0,0,0,2200,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,22.670000,1,2,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,29.250000,0,0,0,0,0,228,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [209]:
X = dataset[['Sex', 'Age', 'Res_status', 'Time_employed', 'Time_bank', 'Liab_ref',
       'Acc_ref', 'Home_Expn', 'Balance', 'governmen', 'military',
       'private_s', 'retired', 'self_empl', 'student', 'unemploye',
       'creative_', 'driver', 'executive', 'guard_etc', 'labourer', 'manager',
       'office_st', 'productio', 'professio', 'sales', 'semi_pro',
       'unemploye']]

y = dataset[['Decision']]

In [210]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [211]:
# applying logistic regression
logistic_regression = LogisticRegression()
regression_model = logistic_regression.fit(X_train,y_train)

regression_model.score(X, y)

C:\Users\devsh\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\devsh\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

0.7948717948717948